language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

install: yarn

script:
  - yarn run docs
  - yarn run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: docs
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/**/*
    skip_cleanup: true
    on:
      tags: true
